(function(){function r(a){window.getHxGridObj=function(c){return a[c]};window.getHxItemById=function(c){try{var b=c.split("@");return"undefined"===typeof a[parseInt(b[1])].items[parseInt(b[0])]?(new t("HxdGrid->Access error. Invalid item id. Itemuid: "+b[0]+" RAW:"+c),0):a[parseInt(b[1])].items[parseInt(b[0])]}catch(d){throw new l("HxdGrid->Access error. Invalid ID format. The correct format is ITEMuid@GRIDuid. Current input "+c+". Exception details "+d);}}}function x(a){function c(){200>new Date-
b?setTimeout(c,200):d=!1;a.resizeEvent()}var b,d=!1;window.addEventListener("resize",function(a){b=new Date;!1===d&&(d=!0,setTimeout(c,200))})}function y(a,c){for(var b,d=0,h=a.childNodes.length;d<h;d++)for(var e=void 0!=a.childNodes[d].className?a.childNodes[d].className.split(" "):[],q=0,f=e.length;q<f;q++)e[q]==c&&(b=a.childNodes[d]);return b}function z(a,c,b){a.innerHTML=c+a.innerHTML+b;return a}function u(a,c,b,d){setTimeout(function(){a.style[b]=c},"undefined"===typeof d?1E3:d)}function l(a){this.message=
a;this.name="HxdException"}function t(a){for(var c="assert cd clear count countReset debug dir dirxml error exception group groupCollapsed groupEnd info log markTimeline profile profileEnd select table time timeEnd timeStamp timeline timelineEnd trace warn".split(" "),b=c.length,d=window.console=window.console||{},h,e=function(){};b--;)h=c[b],d[h]||(d[h]=e);d.log("------WARNING------");d.log(a)}var v=0,w=function(a,c,b){this.domElem=a;this.setOptions(c);this.create(this,b)};w.prototype={uid:0,domElem:null,
xCor:0,yCor:0,gridPadding:5,relW:1,relH:1,viewFade:!0,setOptions:function(a){this.viewFade=a&&a.viewFade||this.viewFade;this.autoBind=a&&a.autoBind||this.autoBind},addAttr:function(a,c){this.hasOwnProperty(a)?new t("HxdError -> Object function. Attempting to override property. Use setAttribute instead"):this[a]=c},passNodeAttributes:function(a){for(var c=0,b=a.length;c<b;c++){var d=a.item(c);-1<d.name.indexOf("data-hxd-")&&this.addAttr(d.name.replace("data-hxd-",""),d.value)}},create:function(a,c){a.relW=
Math.round(a.domElem.offsetWidth/c);a.relH=Math.round(a.domElem.offsetHeight/c);if(1<a.relW){var b=a.gridPadding/c*(a.relW-1);a.relW+=b;a.domElem.style.width=a.relW*c+"px"}1<a.relH&&(b=a.gridPadding/c*(a.relH-1),a.relH+=b,a.domElem.style.height=a.relH*c+"px")},getXY:function(){return[this.xCor,this.yCor]},swapPos:function(a,c){var b=this.getXY(),d=a.getXY();this.moveTo(d[0],d[1]);a.moveTo(b[0],b[1]);var d=this.uid.split("@")[0],b=this.domElem.parentNode,d="binaryShift"+d,h={0:this,1:a},e;document.createEvent?
(e=document.createEvent("HTMLEvents"),e.initEvent("dataavailable",!0,!0,h)):(e=document.createEventObject(),e.eventType="dataavailable");e.eventName=d;document.createEvent?b.dispatchEvent(e):b.fireEvent("on"+e.eventType,e);"undefined"!==typeof c&&c()},moveTo:function(a,c){var b=this.domElem;if("undefined"!==typeof b.getAttribute("style")&&"absolute"==b.style.position)this.animateOver(a,c);else{var d=b.getAttribute("style");b.setAttribute("style",d+"opacity:1;margin:0!important;float:none;position: absolute;left:"+
a+"px;top:"+c+"px")}this.xCor=a;this.yCor=c},animateOver:function(a,c,b){b=b||this.domElem;b.style.WebkitTransition="  all 0.7s ease ";b.style.MozTransition="  all 0.7s ease ";b.style.transition=" all 1s ease  ";a+="px";var d=c+"px";b.style.top<c?(b.style.left!=a&&(b.style.left=a),b.style.top!=d&&u(b,d,"top",1E3)):(b.style.top!=d&&(b.style.top=d),b.style.left!=a&&u(b,a,"left",1E3))},isElementInViewport:function(a,c){var b=this.domElem.getBoundingClientRect();return-100<=b.top&&-100<=b.left&&b.bottom<=
(window.innerHeight+100||document.documentElement.clientHeight+100)&&b.right<=(window.innerWidth+100||document.documentElement.clientWidth+100)},moveInViewport:function(a,c){var b=this.domElem.getBoundingClientRect(),d=parseInt(this.domElem.style.top)-c,h=parseInt(this.domElem.style.left)-a;return 0<=b.top-d&&0<=b.left-h&&b.bottom-d<=(window.innerHeight+0||document.documentElement.clientHeight+0)&&b.right-h<=(window.innerWidth+0||document.documentElement.clientWidth+0)}};var m=function(a,c){try{this.uid=
v;this.domElem=a;this.resizeLock=!0;this.items=[];var b;b=0<window.navigator.userAgent.indexOf("MSIE ")||navigator.userAgent.match(/Trident.*rv\:11\./)?!0:!1;b?a.className+="hxdGridContainer":a.classList.add("hxdGridContainer");a.setAttribute("style","list-style: none;width: 100%; height: 100%; overflow: hidden;  position: relative;");this.setOptions(c);this.create(this);x(this);v++}catch(d){throw new l("HxdGrid-> Grid initialization error. Detais: "+d);}};m.prototype={uid:0,domElem:null,resize:!0,
gridCellSize:80,gridCellsWidth:0,gridPadding:5,selector:".hxdItem",hiddenItems:[],cellOptions:{},setOptions:function(a){this.autocenter=a&&!1!==a.autocenter||!1;this.resize=a&&a.resize||this.resize;this.selector=a&&a.selector||this.selector;this.cellOptions.autoBind=a&&a.autoBind||!1;this.cellOptions.viewFade=a&&a.viewFade||!1},create:function(a){a.reflowLevel=0;a._boundaryWrap(a.domElem,a);for(var c=a.domElem.querySelectorAll(a.selector),b=0,d=c.length;b<d;b++)c[b].innerHTML=b,a.items[b]=new w(c[b],
a.cellOptions,a.gridCellSize);a.positionItems()},_boundaryWrap:function(a,c){this.gridCellsWidth=Math.floor(a.offsetWidth/this.gridCellSize);var b=z(a,"<div class='blockGrid' style='height: 100vh'>","</div>"),d=document.createEvent("Event");d.initEvent("dataavailable",!0,!0);y(b,"blockGrid").addEventListener(d,function(a,b){},!1)},resizeEvent:function(){console.log("resize");this.gridCellsWidth=Math.floor(this.domElem.offsetWidth/this.gridCellSize);this.positionItems()},positionItems:function(){var a=
0,c=0,b={},d=this.items,h;console.log("---------");for(var e=0,q=this.items.length;e<q;e++){0<e&&(a=this.gridPadding+this.gridCellSize*this.items[e-1].relW+this.items[e-1].xCor);a>this.gridCellsWidth*this.gridCellSize&&(a=0,h=b,b={});if("undefined"!==typeof h){var c=h,f=a,p=e,g=f,a=0;if("undefined"!==typeof c[f])if(1<c[f].relH)if(b[g]={relW:c[f].relW,relH:Math.floor(c[f].relH)-1,yCor:c[f].yCor+(this.gridCellSize+this.gridPadding),xCor:c[f].xCor,i:"pseudoB"},a=c[f].yCor+this.gridCellSize+this.gridPadding,
"pseudoB"!==c[f].i||2<=c[f].relH){g=this.gridPadding+this.gridCellSize*c[f].relW+c[f].xCor;var f=this.gridCellSize,p=this.gridPadding,k=c[g];if("undefined"!==typeof k)if(2<=k.relH)for(g=k.xCor+k.relW*f+p;"undefined"!==typeof c[g]&&2<c[g].relH;)k=c[g],g=k.xCor+k.relW*f+p;else g=k.xCor}else console.log(c[f]);else a=c[f].yCor+c[f].relH*this.gridCellSize+this.gridPadding;else a=this.items[p-1].yCor;c=[g,a];a=c[0];c=c[1];a:{var g=h,f=a,p=b,k=e,l=this.items[k];if("undefined"!==typeof g[f]&&1<l.relW)for(var m=
1;m<l.relW;m++){var n=g[f].xCor+m*(this.gridCellSize+this.gridPadding);if("undefined"!==typeof g[n]&&2<=g[n].relH){this.items[k]=this.items[k+1];this.items[k+1]=l;p[n]={relW:g[n].relW,relH:Math.floor(g[n].relH)-1,yCor:g[n].yCor+(this.gridCellSize+this.gridPadding),xCor:g[n].xCor,i:"pseudoB"};g=!0;break a}}g=void 0}g&&console.log("swap "+e+" with"+(e+1))}this.items[e].moveTo(a,c);b[a]={relW:this.items[e].relW,relH:this.items[e].relH,yCor:this.items[e].yCor,xCor:this.items[e].xCor,i:e}}this.items=d}};
"undefined"!==typeof jQuery&&(jQuery.fn.hxdGrid=function(a){var c=[];r(c);return this.each(function(b){c[b]=new m(this,a)})});window.hxdgrid=function(a,c){var b=[];r(b);for(var d=document.querySelectorAll(a),h=0,e=d.length;h<e;h++)b[h]=new m(d[h],c);return 1==e?b[0]:b};l.prototype=Error()})();
