var jQuery=jQuery||require&&require("jquery"),HxdModuleLoader="undefined"===typeof HxdModuleLoader?0:HxdModuleLoader;
(function(r){function y(a){window.getHxGridObj=function(c){return a[c]};window.getHxItemById=function(c){try{var b=c.split("@");return"undefined"===typeof a[parseInt(b[1])].items[parseInt(b[0])]?(m("HxdGrid->Access error. Invalid item id. Itemuid: "+b[0]+" RAW:"+c),0):a[parseInt(b[1])].items[parseInt(b[0])]}catch(d){throw new k("HxdGrid->Access error. Invalid ID format. The correct format is ITEMuid@GRIDuid. Current input "+c+". Exception details "+d);}}}function z(a){function c(){200>new Date-b?
setTimeout(c,200):(d=!1,a.resizeLock&&(a.resizeLock=!1,a.reflowHexRows(function(){a.resizeLock=!0})))}var b,d=!1;window.addEventListener("resize",function(a){b=new Date;!1===d&&(d=!0,setTimeout(c,200))})}function t(a){return/(^#[0-9A-F]{6}$)|(^#[0-9A-F]{3}$)/i.test(a)}function n(a){a=parseInt(a);a=a.toString(16);return 1==a.length?"0"+a:a}function u(a,c){for(var b=0,d=a.childNodes.length;b<d;b++)for(var e=void 0!=a.childNodes[b].className?a.childNodes[b].className.split(" "):[],f=0,h=e.length;f<h;f++)e[f]==
c&&(notes=a.childNodes[b]);return notes}function v(a,c,b,d,e){b=parseInt(b);d=parseInt(d);if(a){var f=(new Date).getTime(),h=setInterval(function(){var g=Math.min(1,((new Date).getTime()-f)/e);a.style[c]=b+g*(d-b)+"px";1==g&&clearInterval(h)},25);a.style[c]=b+"px"}}function l(a,c,b,d){d=d||function(a){return a};b=b||0;var e=[[],[]];if(2>a.length)return a;for(var f=Math.floor(a.length/2),h=d(a[f][c]),f=a.splice(f,1)[0],g=0;g<a.length;g++){var k=d(a[g][c]);k<=h?e[0+b].push(a[g]):k>h&&e[1-b].push(a[g])}return l(e[0],
c,b,d).concat(f,l(e[1],c,b,d))}function p(a){for(var c="width height opacity background-image background-repeat background-position background-color margin-right margin-left margin-top margin-bottom".split(" "),b={},d="undefined"!==getComputedStyle,e=0,f=c.length;e<f;e++)b[c[e]]=d?getComputedStyle(a,null).getPropertyValue(c[e]):a.currentStyle[c[e]];return b}function A(a,c,b){var d={MM:0,YYYY:2,DD:1},e=[];a=a.split(c);b=b.split("-");c=0;for(var f=b.length;c<f;c++)e[d[b[c]]]=a[c];return e.join("/")}
function B(a,c){for(var b=[],d=a.length,e=0;e<d;e++){var f=a[e];c(f)&&b.push(f)}return b}function C(a,c,b){setTimeout(function(){a.style.top=c},"undefined"===typeof b?1E3:b)}function D(a,c,b){setTimeout(function(){a.style.left=c},"undefined"===typeof b?1E3:b)}function E(a,c,b){org_html=a.innerHTML;new_html=c+org_html+b;a.innerHTML=new_html;return a}function k(a){this.message=a;this.name="HxdException"}function m(a){for(var c="assert cd clear count countReset debug dir dirxml error exception group groupCollapsed groupEnd info log markTimeline profile profileEnd select table time timeEnd timeStamp timeline timelineEnd trace warn".split(" "),
b=c.length,d=window.console=window.console||{},e,f=function(){};b--;)e=c[b],d[e]||(d[e]=f);d.log("------WARNING------");d.log(a)}var w=0,x=function(a,c){try{this.uid=w,this.domElem=a,this.resizeLock=!0,this.items=[],a.classList.add("hxdGridContainer"),a.setAttribute("style","list-style: none;width: 100%; height: 100%; overflow: hidden;  position: relative;"),this.setOptions(c),this.create(jQuery,this),z(this),w++}catch(b){throw new k("HxdGrid-> Grid initialization error. Detais: "+b);}},q=function(a,
c){this.$elem=r(a);this.domElem=a;this.cssAnim=!1;var b;b=0<window.navigator.userAgent.indexOf("MSIE ")||navigator.userAgent.match(/Trident.*rv\:11\./)?!0:!1;b&&(this.cssAnim=!1);this.harwareAccelaration=!1;this.setOptions(c);this.create(this)};q.prototype={uid:0,$elem:null,domElem:null,startPos:null,bgColor:0,xCor:0,yCor:0,setOptions:function(a){this.viewFade=a&&a.viewFade||this.viewFade;this.autoBind=a&&a.autoBind||this.autoBind;"undefined"!==typeof a.bgColor&&0!=a.bgColor&&(t(a.bgColor)?this.bgColor=
a&&a.bgColor:m("HxdError -> Options.Invalid color ("+a.bgColor+") provided. Input ignored. Please provide a valid hex string"))},addAttr:function(a,c){this.hasOwnProperty(a)?m("HxdError -> Object function. Attempting to override property. Use setAttribute instead"):this[a]=c},_passNodeAttributes:function(a){for(var c=0,b=a.length;c<b;c++){var d=a.item(c);-1<d.name.indexOf("data-hxd-")&&this.addAttr(d.name.replace("data-hxd-",""),d.value)}},create:function(a){var c="";if("undefined"!==typeof p(a.domElem)["background-color"]){var b;
b=p(a.domElem)["background-color"];if("transparent"==b)b="";else{b=b.split("(")[1].split(")")[0].split(",");var d=b[1],e=b[2];b="#"+n(b[0])+n(d)+n(e)}t(b)&&(a.bgColor=b,c=a.colStyleOverride(a))}modeVar="";a.$elem.wrapInner("<div class='hxContent "+modeVar+"' "+c+"></div>")},getXY:function(){return[this.xCor,this.yCor]},swapPos:function(a,c){var b=this.getXY(),d=a.getXY();this.moveTo(d[0],d[1]);a.moveTo(b[0],b[1]);b=this.uid.split("@")[0];this.$elem.parent().trigger("binaryShift"+b,{0:this,1:a});"undefined"!==
typeof c&&c()},colStyleOverride:function(a){if("undefined"!==typeof a.bgColor&&0!==a.bgColor)return'style="background:'+a.bgColor+'"'},moveTo:function(a,c,b){b=b||this.$elem;var d=b.get(0);"undefined"!==typeof d.getAttribute("style")&&"absolute"==d.style.position?this.moveInViewport(a,c)||!this.viewFade?this.animateOver(a,c):this.cssAnim?this.fadeOver(a,c,d):b.filter(":not(:animated)").fadeOut("normal",function(){b.css({left:a,top:c});b.fadeIn("fast")}):d.setAttribute("style","margin:0!important;float:none;position: absolute;left:"+
a+"px;top:"+c+"px");this.xCor=a;this.yCor=c},animateOver:function(a,c,b){b=b||this.domElem;if(this.cssAnim){this.harwareAccelaration&&(b.style.WebkitTransform="  translate3d(0, 0, 0)",b.style.MozTransform="  translate3d(0, 0, 0) ",b.style.transform=" translate3d(0, 0, 0) ");b.style.WebkitTransition="  all 0.7s ease ";b.style.MozTransition="  all 0.7s ease ";b.style.transition=" all 1s ease  ";a+="px";var d=c+"px";b.style.top<c?(b.style.left!=a&&(b.style.left=a),b.style.top!=d&&C(b,d,1E3)):(b.style.top!=
d&&(b.style.top=d),b.style.left!=a&&D(b,a,1E3))}else v(b,"left",b.style.left,a,500),v(b,"top",b.style.top,c,500)},fadeOver:function(a,c,b){b=b||this.domElem;b.style.WebkitTransition="  opacity  0.7s ease ";b.style.MozTransition="  opacity  0.7s ease ";b.style.transition=" opacity  1 linear 0s ";b.style.opacity="0";this.delayedOpacityShift(b,2,1500,a,c)},delayedOpacityShift:function(a,c,b,d,e){setTimeout(function(){var b=e+"px";a.style.left=d+"px";a.style.top=b;a.style.opacity="1"},"undefined"===typeof b?
1E3:b)},forceHidden:function(){this.$elem.fadeOut("slow","linear")},forceVisible:function(){this.$elem.fadeIn("slow","linear")},toggleVisible:function(a){this.$elem.fadeToggle("slow","linear")},isElementInViewport:function(a,c){el=this.$elem;var b=el[0].getBoundingClientRect();return-100<=b.top&&-100<=b.left&&b.bottom<=(window.innerHeight+100||document.documentElement.clientHeight+100)&&b.right<=(window.innerWidth+100||document.documentElement.clientWidth+100)},moveInViewport:function(a,c){el=this.$elem;
var b=el[0].getBoundingClientRect(),d=parseInt(el[0].style.top)-c,e=parseInt(el[0].style.left)-a;return 0<=b.top-d&&0<=b.left-e&&b.bottom-d<=(window.innerHeight+0||document.documentElement.clientHeight+0)&&b.right-e<=(window.innerWidth+0||document.documentElement.clientWidth+0)},hxGetYOffset:function(a){var c=1.015*parseInt(a.height);return[function(a){return c*a},function(b){return c*b+(parseInt(a["margin-top"])||0)}]}};x.prototype={uid:0,domElem:null,resize:!0,selector:".hxdItem",hiddenItems:[],
gridId:null,emptyGrid:!1,emptyGridLength:0,reflowLock:!0,cellStyle:0,cellOptions:{},setOptions:function(a){this.autocenter=a&&!1!==a.autocenter||!1;this.clipping=a&&a.clipping||this.clipping;this.resize=a&&a.resize||this.resize;this.selector=a&&a.selector||this.selector;this.hexMode=a&&a.hexMode||this.hexMode;this.reflowLock=a&&a.reflowLock||this.reflowLock;this.emptyGrid=a&&a.emptyGrid||this.emptyGrid;this.emptyGridLength=a&&a.emptyGridLength||this.emptyGridLength;this.cellOptions.hxScale=a&&a.hxScale||
"hxd-xl";this.cellOptions.autoBind=a&&a.autoBind||!1;this.cellOptions.bgColor=a&&a.bgColor||0;this.cellOptions.viewFade=a&&a.viewFade||!1},create:function(a,c){c.reflowLevel=0;c._boundaryWrap(c.domElem,c);var b;b=c.domElem.querySelectorAll(c.selector);for(var d=0,e=b.length;d<e;d++){var f=b[d];c.items[d]=0!==HxdModuleLoader?HxdModuleLoader.moduleSelect(c,c.cellOptions,r(f),q):new q(f,c.cellOptions);c.items[d].uid=c.uid+"@"+d;c.items[d]._passNodeAttributes(f.attributes)}if(0==c.cellStyle){b=1<c.items.length?
1:0;if(0==b)throw new k("OPS one item in the grid. Are you sure you have it on the right dom element");c.cellStyle=p(c.items[b].domElem);"undefined"===typeof c.cellStyle.height&&(c.cellStyle.height=c.cellStyle.width)}c.xyMap=c.mapGrid();c._prepContainer();c.reflowHexRows()},_prepContainer:function(){boundingH=this.xyMap.rows*parseInt(this.cellStyle.height)+(parseInt(this.cellStyle["margin-top"])||0);u(this.domElem,"gridContent").setAttribute("style","position:relative;width:100%;height:"+boundingH+
"px")},_boundaryWrap:function(a,c){c=c||this;out=E(a,"<div class='gridContent'>","</div>");var b="binaryShift"+c.uid;u(out,"gridContent").addEventListener(b,function(a,b){c.orderSwap(b)},!1)},orderSwap:function(a){var c=a[0].startPos;a=a[1].startPos;this.itemOrder[c]=a;this.itemOrder[a]=c},reflowHexRows:function(a){this.reflowLock&&(this.reflowLock=!1,this.xyMap=this.mapGrid(),this.reflowLevel!=this.xyMap.rows&&(this._prepContainer(),reflowLevel=this.xyMap.rows,this.reflowCells(this.itemOrder)),this.reflowLock=
!0,"undefined"!==typeof a&&a())},reflowCells:function(a){"undefined"===typeof this.itemOrder&&(this.itemOrder=[]);for(var c=0,b=this.items.length;c<b;c++){var d="undefined"===typeof a||"undefined"===typeof a[c]?c:a[c];if("undefined"!==typeof this.xyMap.cols||0!=this.xyMap.cols){0<this.hiddenItems.indexOf(d)?this.items[d].toggleVisible():this.items[d].forceVisible();if(1==this.emptyGrid)var e=this.items[d].setrow,f=this.items[d].setcol%this.xyMap.cols;else e=Math.ceil((c+1)/this.xyMap.cols),f=c%this.xyMap.cols;
var h=f*this.xyMap.xO+this.xyMap.xIndent;if(!isNaN(f))var g=this.xyMap.yO[f%2](e-1);"undefined"!==typeof f&&"undefined"!==typeof g||this.items[d].forceHidden();this.items[d].moveTo(h,g)}this.items[d].startPos=d;this.itemOrder[c]=d}},grepItems:function(a,c){return B(this.items,function(b){return"undefined"!==typeof c?b[a]===c:b[a]})},orderByDateKey:function(a,c,b,d,e){c=c||!1;b=b||"ascending";d=d||".";e=e||"DD-MM-YYYY";var f=l(this.grepItems(a),a),f=function(a){return Date.parse(A(a,d,e))},f="descending"==
b?l(this.grepItems(a),a,1,f):l(this.grepItems(a),a,0,f);this._orderChange(f,c)},orderByKey:function(a,c,b){c=c||!1;a="descending"==(b||"ascending")?l(this.grepItems(a),a,1):l(this.grepItems(a),a);this._orderChange(a,c)},_orderChange:function(a,c){for(var b=[],d=[],e=0,f=a.length;e<f;e++)b[e]=a[e].startPos;e=0;for(f=this.itemOrder.length;e<f;e++)-1==b.indexOf(e)&&(b.push(e),c&&d.push(e));c&&(this.hiddenItems=d);this.itemOrder=b;this.reflowCells(this.itemOrder)},randomShuffle:function(){for(var a=this.itemOrder,
c=a.length-1;0<c;c--){var b=Math.floor(Math.random()*(c+1)),d=a[c];a[c]=a[b];a[b]=d}this.reflowCells(a)},resetOrder:function(){for(var a=0,c=this.itemOrder.length;a<c;a++)this.itemOrder[a]=a;this.hiddenItems=[];this.reflowCells(this.itemOrder)},mapGrid:function(){var a=this.domElem.offsetWidth,c=this.emptyGrid&&0<this.emptyGridLength?this.emptyGridLength:this.items.length,b=parseInt(this.cellStyle["margin-left"]||0);parseInt(this.cellStyle["margin-right"]||0);var d=parseInt(this.cellStyle.width)+
b,e=Math.floor(a/d);this.autocenter?(a=(a-e*d)/2,a=a>2*Math.abs(b)?a-b:a+b/2,c<e&&(a+=(e-c)/2*d)):a=0;return{cols:e,rows:Math.ceil(c/e),xO:d,yO:this.items[1<this.items.length?1:0].hxGetYOffset(this.cellStyle),xIndent:a}}};jQuery.fn.hxdGrid=function(a){var c=[];y(c);return this.each(function(b){c[b]=new x(this,a)})};k.prototype=Error()})(jQuery);
